//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkpoint.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebApiMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebApiMethods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("checkpoint.Resources.WebApiMethods", typeof(WebApiMethods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddCompra?orden=.
        /// </summary>
        internal static string AddCompra {
            get {
                return ResourceManager.GetString("AddCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddOrders.
        /// </summary>
        internal static string AddOrders {
            get {
                return ResourceManager.GetString("AddOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddVenta.
        /// </summary>
        internal static string AddVenta {
            get {
                return ResourceManager.GetString("AddVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalcIvaReturn.
        /// </summary>
        internal static string CalcIvaReturn {
            get {
                return ResourceManager.GetString("CalcIvaReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalcIvaTasa.
        /// </summary>
        internal static string CalcIvaTasa {
            get {
                return ResourceManager.GetString("CalcIvaTasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelaVenta.
        /// </summary>
        internal static string CancelaVenta {
            get {
                return ResourceManager.GetString("CancelaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteImpuestoProductoById?idImpuestoProducto=.
        /// </summary>
        internal static string DeleteImpuestoProductoById {
            get {
                return ResourceManager.GetString("DeleteImpuestoProductoById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletePantallaUsuario?idPantallaUsuario=.
        /// </summary>
        internal static string DeletePantallaUsuario {
            get {
                return ResourceManager.GetString("DeletePantallaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletePluProductoById?idPlu=.
        /// </summary>
        internal static string DeletePluProductoById {
            get {
                return ResourceManager.GetString("DeletePluProductoById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProductoProveedor.
        /// </summary>
        internal static string DeleteProductoProveedor {
            get {
                return ResourceManager.GetString("DeleteProductoProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProductoProveedorById?idProductoProveedor=.
        /// </summary>
        internal static string DeleteProductoProveedorById {
            get {
                return ResourceManager.GetString("DeleteProductoProveedorById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteProductPromotion?idProductoPromocion=.
        /// </summary>
        internal static string DeleteProductPromotion {
            get {
                return ResourceManager.GetString("DeleteProductPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllAlmacenes.
        /// </summary>
        internal static string GetAllAlmacenes {
            get {
                return ResourceManager.GetString("GetAllAlmacenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllCashIncomes?idcorte=.
        /// </summary>
        internal static string GetAllCashIncomes {
            get {
                return ResourceManager.GetString("GetAllCashIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllCatalogoSat.
        /// </summary>
        internal static string GetAllCatalogoSat {
            get {
                return ResourceManager.GetString("GetAllCatalogoSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllDepartamentos.
        /// </summary>
        internal static string GetAllDepartamentos {
            get {
                return ResourceManager.GetString("GetAllDepartamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllImpuestos.
        /// </summary>
        internal static string GetAllImpuestos {
            get {
                return ResourceManager.GetString("GetAllImpuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllMarcas.
        /// </summary>
        internal static string GetAllMarcas {
            get {
                return ResourceManager.GetString("GetAllMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllOrders.
        /// </summary>
        internal static string GetAllOrders {
            get {
                return ResourceManager.GetString("GetAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllPagosCorte.
        /// </summary>
        internal static string GetAllPagosCorte {
            get {
                return ResourceManager.GetString("GetAllPagosCorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllPantallas.
        /// </summary>
        internal static string GetAllPantallas {
            get {
                return ResourceManager.GetString("GetAllPantallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllPantallasByUser?idUsuario=.
        /// </summary>
        internal static string GetAllPantallasByUser {
            get {
                return ResourceManager.GetString("GetAllPantallasByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllPrincipalPantallas.
        /// </summary>
        internal static string GetAllPrincipalPantallas {
            get {
                return ResourceManager.GetString("GetAllPrincipalPantallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllPrincipalPantallasByUser?idUsuario=.
        /// </summary>
        internal static string GetAllPrincipalPantallasByUser {
            get {
                return ResourceManager.GetString("GetAllPrincipalPantallasByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllProducts.
        /// </summary>
        internal static string GetAllProducts {
            get {
                return ResourceManager.GetString("GetAllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllProductsByDepartment?idDepartamento=.
        /// </summary>
        internal static string GetAllProductsByDepartment {
            get {
                return ResourceManager.GetString("GetAllProductsByDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllPromociones.
        /// </summary>
        internal static string GetAllPromociones {
            get {
                return ResourceManager.GetString("GetAllPromociones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllProveedores.
        /// </summary>
        internal static string GetAllProveedores {
            get {
                return ResourceManager.GetString("GetAllProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllRetiros?idcorte=.
        /// </summary>
        internal static string GetAllRetiros {
            get {
                return ResourceManager.GetString("GetAllRetiros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllSubPantallas.
        /// </summary>
        internal static string GetAllSubPantallas {
            get {
                return ResourceManager.GetString("GetAllSubPantallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllTaxes.
        /// </summary>
        internal static string GetAllTaxes {
            get {
                return ResourceManager.GetString("GetAllTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllTipoPago.
        /// </summary>
        internal static string GetAllTipoPago {
            get {
                return ResourceManager.GetString("GetAllTipoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllTurns.
        /// </summary>
        internal static string GetAllTurns {
            get {
                return ResourceManager.GetString("GetAllTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUnidades.
        /// </summary>
        internal static string GetAllUnidades {
            get {
                return ResourceManager.GetString("GetAllUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUnidadesSat.
        /// </summary>
        internal static string GetAllUnidadesSat {
            get {
                return ResourceManager.GetString("GetAllUnidadesSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUserTypes.
        /// </summary>
        internal static string GetAllUserTypes {
            get {
                return ResourceManager.GetString("GetAllUserTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUsuarios.
        /// </summary>
        internal static string GetAllUsuarios {
            get {
                return ResourceManager.GetString("GetAllUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllUsuariosWithPermissions.
        /// </summary>
        internal static string GetAllUsuariosWithPermissions {
            get {
                return ResourceManager.GetString("GetAllUsuariosWithPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBrandsByName?brandName=.
        /// </summary>
        internal static string GetBrandsByName {
            get {
                return ResourceManager.GetString("GetBrandsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCatalogByClave?claveCatalogo=.
        /// </summary>
        internal static string GetCatalogByClave {
            get {
                return ResourceManager.GetString("GetCatalogByClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCatalogByName?catalogName=.
        /// </summary>
        internal static string GetCatalogByName {
            get {
                return ResourceManager.GetString("GetCatalogByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCurrentCashClose?idUsuario=.
        /// </summary>
        internal static string GetCurrentCashClose {
            get {
                return ResourceManager.GetString("GetCurrentCashClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDepartmenByName?name=.
        /// </summary>
        internal static string GetDepartmenByName {
            get {
                return ResourceManager.GetString("GetDepartmenByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetImpuestoByName?name=.
        /// </summary>
        internal static string GetImpuestoByName {
            get {
                return ResourceManager.GetString("GetImpuestoByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLastFolio.
        /// </summary>
        internal static string GetLastFolio {
            get {
                return ResourceManager.GetString("GetLastFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetOrdersByEstatusWithSupplier?estatusSearch=.
        /// </summary>
        internal static string GetOrdersByEstatusWithSupplier {
            get {
                return ResourceManager.GetString("GetOrdersByEstatusWithSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPantallasByUserId?userId=.
        /// </summary>
        internal static string GetPantallasByUserId {
            get {
                return ResourceManager.GetString("GetPantallasByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPaymentByName?name=.
        /// </summary>
        internal static string GetPaymentByName {
            get {
                return ResourceManager.GetString("GetPaymentByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductosByName?nombre=.
        /// </summary>
        internal static string GetProdcutByName {
            get {
                return ResourceManager.GetString("GetProdcutByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductoByPLU?PLU=.
        /// </summary>
        internal static string GetProductByPLU {
            get {
                return ResourceManager.GetString("GetProductByPLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductObjectByPLU?plu=.
        /// </summary>
        internal static string GetProductObjectByPLU {
            get {
                return ResourceManager.GetString("GetProductObjectByPLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductosByAlmacen?idAlmacen=.
        /// </summary>
        internal static string GetProductosByAlmacen {
            get {
                return ResourceManager.GetString("GetProductosByAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductoWithSuppliers?pluProducto=.
        /// </summary>
        internal static string GetProductoWithSuppliers {
            get {
                return ResourceManager.GetString("GetProductoWithSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductsByList.
        /// </summary>
        internal static string GetProductsByList {
            get {
                return ResourceManager.GetString("GetProductsByList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProductsSuggestToBuy?supplier=.
        /// </summary>
        internal static string GetProductsSuggestToBuy {
            get {
                return ResourceManager.GetString("GetProductsSuggestToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPromocionById?idPromocion=.
        /// </summary>
        internal static string GetPromocionById {
            get {
                return ResourceManager.GetString("GetPromocionById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetReturnsWithTaxes.
        /// </summary>
        internal static string GetReturnsWithTaxes {
            get {
                return ResourceManager.GetString("GetReturnsWithTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetScreenByName?screenName=.
        /// </summary>
        internal static string GetScreenByName {
            get {
                return ResourceManager.GetString("GetScreenByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSuppliersByName?name=.
        /// </summary>
        internal static string GetSuppliersByName {
            get {
                return ResourceManager.GetString("GetSuppliersByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSuppliersWithProducts.
        /// </summary>
        internal static string GetSuppliersWithProducts {
            get {
                return ResourceManager.GetString("GetSuppliersWithProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTotalEfectivo?idUsuario=.
        /// </summary>
        internal static string GetTotalEfectivo {
            get {
                return ResourceManager.GetString("GetTotalEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTotalReturns.
        /// </summary>
        internal static string GetTotalReturns {
            get {
                return ResourceManager.GetString("GetTotalReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTotalSale.
        /// </summary>
        internal static string GetTotalSale {
            get {
                return ResourceManager.GetString("GetTotalSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTotalTaxes.
        /// </summary>
        internal static string GetTotalTaxes {
            get {
                return ResourceManager.GetString("GetTotalTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTotalWithTaxes.
        /// </summary>
        internal static string GetTotalWithTaxes {
            get {
                return ResourceManager.GetString("GetTotalWithTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTurnsByName?turnName=.
        /// </summary>
        internal static string GetTurnsByName {
            get {
                return ResourceManager.GetString("GetTurnsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUnidadesSatByid?unitSatId=.
        /// </summary>
        internal static string GetUnidadesSatByid {
            get {
                return ResourceManager.GetString("GetUnidadesSatByid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUnitsByName?unitName=.
        /// </summary>
        internal static string GetUnitsByName {
            get {
                return ResourceManager.GetString("GetUnitsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUnitsSatByName?unitName=.
        /// </summary>
        internal static string GetUnitsSatByName {
            get {
                return ResourceManager.GetString("GetUnitsSatByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserAdmin.
        /// </summary>
        internal static string GetUserAdmin {
            get {
                return ResourceManager.GetString("GetUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUsuarioByName?name=.
        /// </summary>
        internal static string GetUsuarioByName {
            get {
                return ResourceManager.GetString("GetUsuarioByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUsuarioByUserName?userName=.
        /// </summary>
        internal static string GetUsuarioByUserName {
            get {
                return ResourceManager.GetString("GetUsuarioByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVentaByFolioVenta?folioVenta=.
        /// </summary>
        internal static string GetVentaByFolioVenta {
            get {
                return ResourceManager.GetString("GetVentaByFolioVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveBrand.
        /// </summary>
        internal static string SaveBrand {
            get {
                return ResourceManager.GetString("SaveBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveCashClose.
        /// </summary>
        internal static string SaveCashClose {
            get {
                return ResourceManager.GetString("SaveCashClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveCatalogSat.
        /// </summary>
        internal static string SaveCatalogSat {
            get {
                return ResourceManager.GetString("SaveCatalogSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveDepartamento.
        /// </summary>
        internal static string SaveDepartamento {
            get {
                return ResourceManager.GetString("SaveDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveImpuesto.
        /// </summary>
        internal static string SaveImpuesto {
            get {
                return ResourceManager.GetString("SaveImpuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavePayment.
        /// </summary>
        internal static string SavePayment {
            get {
                return ResourceManager.GetString("SavePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveProduct.
        /// </summary>
        internal static string SaveProduct {
            get {
                return ResourceManager.GetString("SaveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveProducts.
        /// </summary>
        internal static string SaveProducts {
            get {
                return ResourceManager.GetString("SaveProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavePromocion.
        /// </summary>
        internal static string SavePromocion {
            get {
                return ResourceManager.GetString("SavePromocion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveProveedor.
        /// </summary>
        internal static string SaveProveedor {
            get {
                return ResourceManager.GetString("SaveProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveRetiro.
        /// </summary>
        internal static string SaveRetiro {
            get {
                return ResourceManager.GetString("SaveRetiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveScreen.
        /// </summary>
        internal static string SaveScreen {
            get {
                return ResourceManager.GetString("SaveScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveTurn.
        /// </summary>
        internal static string SaveTurn {
            get {
                return ResourceManager.GetString("SaveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveUnit.
        /// </summary>
        internal static string SaveUnit {
            get {
                return ResourceManager.GetString("SaveUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveUnitSat.
        /// </summary>
        internal static string SaveUnitSat {
            get {
                return ResourceManager.GetString("SaveUnitSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveUser.
        /// </summary>
        internal static string SaveUser {
            get {
                return ResourceManager.GetString("SaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateOrder.
        /// </summary>
        internal static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateUserPermissionsScreens.
        /// </summary>
        internal static string UpdateUserPermissionsScreens {
            get {
                return ResourceManager.GetString("UpdateUserPermissionsScreens", resourceCulture);
            }
        }
    }
}
