//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkpoint.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebApiMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebApiMethods() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("checkpoint.Resources.WebApiMethods", typeof(WebApiMethods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AddCompra?orden=.
        /// </summary>
        internal static string AddCompra {
            get {
                return ResourceManager.GetString("AddCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AddOrders.
        /// </summary>
        internal static string AddOrders {
            get {
                return ResourceManager.GetString("AddOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AddVenta.
        /// </summary>
        internal static string AddVenta {
            get {
                return ResourceManager.GetString("AddVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CalcIvaReturn.
        /// </summary>
        internal static string CalcIvaReturn {
            get {
                return ResourceManager.GetString("CalcIvaReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CalcIvaTasa.
        /// </summary>
        internal static string CalcIvaTasa {
            get {
                return ResourceManager.GetString("CalcIvaTasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CancelaVenta.
        /// </summary>
        internal static string CancelaVenta {
            get {
                return ResourceManager.GetString("CancelaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DeleteImpuestoProductoById?idImpuestoProducto=.
        /// </summary>
        internal static string DeleteImpuestoProductoById {
            get {
                return ResourceManager.GetString("DeleteImpuestoProductoById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DeletePluProductoById?idPlu=.
        /// </summary>
        internal static string DeletePluProductoById {
            get {
                return ResourceManager.GetString("DeletePluProductoById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DeleteProductoProveedor.
        /// </summary>
        internal static string DeleteProductoProveedor {
            get {
                return ResourceManager.GetString("DeleteProductoProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DeleteProductoProveedorById?idProductoProveedor=.
        /// </summary>
        internal static string DeleteProductoProveedorById {
            get {
                return ResourceManager.GetString("DeleteProductoProveedorById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllCashIncomes?idcorte=.
        /// </summary>
        internal static string GetAllCashIncomes {
            get {
                return ResourceManager.GetString("GetAllCashIncomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllCatalogoSat.
        /// </summary>
        internal static string GetAllCatalogoSat {
            get {
                return ResourceManager.GetString("GetAllCatalogoSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllDepartamentos.
        /// </summary>
        internal static string GetAllDepartamentos {
            get {
                return ResourceManager.GetString("GetAllDepartamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllImpuestos.
        /// </summary>
        internal static string GetAllImpuestos {
            get {
                return ResourceManager.GetString("GetAllImpuestos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllMarcas.
        /// </summary>
        internal static string GetAllMarcas {
            get {
                return ResourceManager.GetString("GetAllMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllOrders.
        /// </summary>
        internal static string GetAllOrders {
            get {
                return ResourceManager.GetString("GetAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllPagosCorte.
        /// </summary>
        internal static string GetAllPagosCorte {
            get {
                return ResourceManager.GetString("GetAllPagosCorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllPantallas.
        /// </summary>
        internal static string GetAllPantallas {
            get {
                return ResourceManager.GetString("GetAllPantallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllPrincipalPantallas.
        /// </summary>
        internal static string GetAllPrincipalPantallas {
            get {
                return ResourceManager.GetString("GetAllPrincipalPantallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllProducts.
        /// </summary>
        internal static string GetAllProducts {
            get {
                return ResourceManager.GetString("GetAllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllProductsByDepartment?idDepartamento=.
        /// </summary>
        internal static string GetAllProductsByDepartment {
            get {
                return ResourceManager.GetString("GetAllProductsByDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllProveedores.
        /// </summary>
        internal static string GetAllProveedores {
            get {
                return ResourceManager.GetString("GetAllProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllRetiros?idcorte=.
        /// </summary>
        internal static string GetAllRetiros {
            get {
                return ResourceManager.GetString("GetAllRetiros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllSubPantallas.
        /// </summary>
        internal static string GetAllSubPantallas {
            get {
                return ResourceManager.GetString("GetAllSubPantallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllTaxes.
        /// </summary>
        internal static string GetAllTaxes {
            get {
                return ResourceManager.GetString("GetAllTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllTipoPago.
        /// </summary>
        internal static string GetAllTipoPago {
            get {
                return ResourceManager.GetString("GetAllTipoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllTurns.
        /// </summary>
        internal static string GetAllTurns {
            get {
                return ResourceManager.GetString("GetAllTurns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllUnidades.
        /// </summary>
        internal static string GetAllUnidades {
            get {
                return ResourceManager.GetString("GetAllUnidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllUnidadesSat.
        /// </summary>
        internal static string GetAllUnidadesSat {
            get {
                return ResourceManager.GetString("GetAllUnidadesSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetAllUsuarios.
        /// </summary>
        internal static string GetAllUsuarios {
            get {
                return ResourceManager.GetString("GetAllUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetBrandsByName?brandName=.
        /// </summary>
        internal static string GetBrandsByName {
            get {
                return ResourceManager.GetString("GetBrandsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetCatalogByName?catalogName=.
        /// </summary>
        internal static string GetCatalogByName {
            get {
                return ResourceManager.GetString("GetCatalogByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetCurrentCashClose?idUsuario=.
        /// </summary>
        internal static string GetCurrentCashClose {
            get {
                return ResourceManager.GetString("GetCurrentCashClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetDepartmenByName?name=.
        /// </summary>
        internal static string GetDepartmenByName {
            get {
                return ResourceManager.GetString("GetDepartmenByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetImpuestoByName?name=.
        /// </summary>
        internal static string GetImpuestoByName {
            get {
                return ResourceManager.GetString("GetImpuestoByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetLastFolio.
        /// </summary>
        internal static string GetLastFolio {
            get {
                return ResourceManager.GetString("GetLastFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetOrdersByEstatusWithSupplier?estatusSearch=.
        /// </summary>
        internal static string GetOrdersByEstatusWithSupplier {
            get {
                return ResourceManager.GetString("GetOrdersByEstatusWithSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetPaymentByName?name=.
        /// </summary>
        internal static string GetPaymentByName {
            get {
                return ResourceManager.GetString("GetPaymentByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetProductosByName?nombre=.
        /// </summary>
        internal static string GetProdcutByName {
            get {
                return ResourceManager.GetString("GetProdcutByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetProductoByPLU?PLU=.
        /// </summary>
        internal static string GetProductByPLU {
            get {
                return ResourceManager.GetString("GetProductByPLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetProductObjectByPLU?plu=.
        /// </summary>
        internal static string GetProductObjectByPLU {
            get {
                return ResourceManager.GetString("GetProductObjectByPLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetProductoWithSuppliers?pluProducto=.
        /// </summary>
        internal static string GetProductoWithSuppliers {
            get {
                return ResourceManager.GetString("GetProductoWithSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetProductsByList.
        /// </summary>
        internal static string GetProductsByList {
            get {
                return ResourceManager.GetString("GetProductsByList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetProductsSuggestToBuy?supplier=.
        /// </summary>
        internal static string GetProductsSuggestToBuy {
            get {
                return ResourceManager.GetString("GetProductsSuggestToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetReturnsWithTaxes.
        /// </summary>
        internal static string GetReturnsWithTaxes {
            get {
                return ResourceManager.GetString("GetReturnsWithTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetScreenByName?screenName=.
        /// </summary>
        internal static string GetScreenByName {
            get {
                return ResourceManager.GetString("GetScreenByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetSuppliersByName?name=.
        /// </summary>
        internal static string GetSuppliersByName {
            get {
                return ResourceManager.GetString("GetSuppliersByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetSuppliersWithProducts.
        /// </summary>
        internal static string GetSuppliersWithProducts {
            get {
                return ResourceManager.GetString("GetSuppliersWithProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetTotalReturns.
        /// </summary>
        internal static string GetTotalReturns {
            get {
                return ResourceManager.GetString("GetTotalReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetTotalSale.
        /// </summary>
        internal static string GetTotalSale {
            get {
                return ResourceManager.GetString("GetTotalSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetTotalTaxes.
        /// </summary>
        internal static string GetTotalTaxes {
            get {
                return ResourceManager.GetString("GetTotalTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetTotalWithTaxes.
        /// </summary>
        internal static string GetTotalWithTaxes {
            get {
                return ResourceManager.GetString("GetTotalWithTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetTurnsByName?turnName=.
        /// </summary>
        internal static string GetTurnsByName {
            get {
                return ResourceManager.GetString("GetTurnsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetUnidadesSatByid?unitSatId=.
        /// </summary>
        internal static string GetUnidadesSatByid {
            get {
                return ResourceManager.GetString("GetUnidadesSatByid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetUnitsByName?unitName=.
        /// </summary>
        internal static string GetUnitsByName {
            get {
                return ResourceManager.GetString("GetUnitsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetUnitsSatByName?unitName=.
        /// </summary>
        internal static string GetUnitsSatByName {
            get {
                return ResourceManager.GetString("GetUnitsSatByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetUserAdmin.
        /// </summary>
        internal static string GetUserAdmin {
            get {
                return ResourceManager.GetString("GetUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetUsuarioByName?name=.
        /// </summary>
        internal static string GetUsuarioByName {
            get {
                return ResourceManager.GetString("GetUsuarioByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GetUsuarioByUserName?userName=.
        /// </summary>
        internal static string GetUsuarioByUserName {
            get {
                return ResourceManager.GetString("GetUsuarioByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveBrand.
        /// </summary>
        internal static string SaveBrand {
            get {
                return ResourceManager.GetString("SaveBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveCashClose.
        /// </summary>
        internal static string SaveCashClose {
            get {
                return ResourceManager.GetString("SaveCashClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveCatalogSat.
        /// </summary>
        internal static string SaveCatalogSat {
            get {
                return ResourceManager.GetString("SaveCatalogSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveDepartamento.
        /// </summary>
        internal static string SaveDepartamento {
            get {
                return ResourceManager.GetString("SaveDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveImpuesto.
        /// </summary>
        internal static string SaveImpuesto {
            get {
                return ResourceManager.GetString("SaveImpuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SavePayment.
        /// </summary>
        internal static string SavePayment {
            get {
                return ResourceManager.GetString("SavePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveProduct.
        /// </summary>
        internal static string SaveProduct {
            get {
                return ResourceManager.GetString("SaveProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveProveedor.
        /// </summary>
        internal static string SaveProveedor {
            get {
                return ResourceManager.GetString("SaveProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveRetiro.
        /// </summary>
        internal static string SaveRetiro {
            get {
                return ResourceManager.GetString("SaveRetiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveScreen.
        /// </summary>
        internal static string SaveScreen {
            get {
                return ResourceManager.GetString("SaveScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveTurn.
        /// </summary>
        internal static string SaveTurn {
            get {
                return ResourceManager.GetString("SaveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveUnit.
        /// </summary>
        internal static string SaveUnit {
            get {
                return ResourceManager.GetString("SaveUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveUnitSat.
        /// </summary>
        internal static string SaveUnitSat {
            get {
                return ResourceManager.GetString("SaveUnitSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SaveUser.
        /// </summary>
        internal static string SaveUser {
            get {
                return ResourceManager.GetString("SaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UpdateOrder.
        /// </summary>
        internal static string UpdateOrder {
            get {
                return ResourceManager.GetString("UpdateOrder", resourceCulture);
            }
        }
    }
}
